modLoader="javafml"
loaderVersion="[2,)"
license="All Rights Reserved"

[[mods]]
modId="wilderness_oddesy_api"
version="0.9.2"
displayName="Wilderness Oddesy API"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator but i codded all the parts to the mod"
authors="thunderrock424242"
description="this is a mod made for the modpack wilderness odessy. it has opomizations and mixins to make your experince better."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.wilderness_oddesy_api]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.117,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.wilderness_oddesy_api]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.wilderness_oddesy_api]]
    modId="geckolib"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


[[mixins]]
    config="mixins.wilderness_oddesy_api.json"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration